version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    environment:
      - PYTHONPATH=/app
      - PROXY_HOST=warp
      - PROXY_PORT=1080
    restart: always
    networks:
      - app_network
    dns:
      - 8.8.8.8
      - 8.8.4.4

networks:
  app_network:
    driver: bridge